name: halley
description: "Seu comércio!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  sign_in_button: ^3.2.0
  google_sign_in_web: ^0.12.4+2
  google_fonts: ^6.2.1
  adaptive_theme: ^3.6.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/halley_logo.svg