// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBstYptb1wOiGOXTT-AoJOx_kr5ReraBys',
    appId: '1:679416549110:web:ba8b54f600efd3625ea6d7',
    messagingSenderId: '679416549110',
    projectId: 'halley-14447',
    authDomain: 'halley-14447.firebaseapp.com',
    storageBucket: 'halley-14447.appspot.com',
    measurementId: 'G-VRQ77JMZ6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL8Kgx-5eLpEFtRxkjeaRMqgenCsBWI6s',
    appId: '1:679416549110:android:057781d8790816ba5ea6d7',
    messagingSenderId: '679416549110',
    projectId: 'halley-14447',
    storageBucket: 'halley-14447.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgjB1Od6ukUkJqSDOqRVxP0BRmqeHYO8Q',
    appId: '1:679416549110:ios:716ed57ba23cad135ea6d7',
    messagingSenderId: '679416549110',
    projectId: 'halley-14447',
    storageBucket: 'halley-14447.appspot.com',
    iosBundleId: 'com.envoy.halley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgjB1Od6ukUkJqSDOqRVxP0BRmqeHYO8Q',
    appId: '1:679416549110:ios:716ed57ba23cad135ea6d7',
    messagingSenderId: '679416549110',
    projectId: 'halley-14447',
    storageBucket: 'halley-14447.appspot.com',
    iosBundleId: 'com.envoy.halley',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBstYptb1wOiGOXTT-AoJOx_kr5ReraBys',
    appId: '1:679416549110:web:bd55173fc435c7815ea6d7',
    messagingSenderId: '679416549110',
    projectId: 'halley-14447',
    authDomain: 'halley-14447.firebaseapp.com',
    storageBucket: 'halley-14447.appspot.com',
    measurementId: 'G-TK6SCDH5EM',
  );
}
